version: "3"
services:
  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4_container
  #  restart: always
  #  ports:
  #    - "8123:80"
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=admin@local.com
  #    - PGADMIN_DEFAULT_PASSWORD=postgres
  #  networks:
  #    - broadcast-bot
  db:
    image: postgres:latest
    networks:
      - broadcast-bot
    environment:
      - PGUSER=admin
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    image: bot-backend-dev:dev01
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8888:8888"
    depends_on:
      - db
    networks:
      - broadcast-bot
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
networks:
  broadcast-bot:
    name: botnet
    external: true
