version: "3.8"
services:
  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4_container
  #  restart: always
  #  ports:
  #    - "8123:80"
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=admin@local.com
  #    - PGADMIN_DEFAULT_PASSWORD=postgres
  #  networks:
  #    - broadcast-bot
  # each bot has its own database
  db:
    image: postgres:latest
    container_name: psql_database
    restart: unless-stopped
    networks:
      - broadcast-bot
    environment:
      - PGUSER=admin
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: bot-backend-dev:dev01
    container_name: bot01-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8888:8888"
    depends_on:
      - db
    networks:
      - broadcast-bot
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
networks:
  broadcast-bot:
    name: botnet
    external: true
volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker/wire/volumes/psql_db/
