version: "3"
services:
  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4_container
  #  restart: always
  #  ports:
  #    - "8888:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@local.com
  #    PGADMIN_DEFAULT_PASSWORD: postgres
  db:
    image: postgres:latest
    environment:
      - PGUSER=admin
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    image: bot-backend-dev:dev01
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db